#!/bin/bash

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Some more ls aliases
alias ll='ls -alFh'
alias la='ls -Ah'
alias l='ls -CFlh'
alias c='clear'

# Command shortcuts
alias py="python3"
alias py2="python2"
alias py3="python3"

alias ..="cd .."
alias ...="cd ../.."
